# Generated by Django 3.2.24 on 2024-02-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_model',
            old_name='id',
            new_name='taks_id',
        ),
    ]
